# Generated by Django 3.0.8 on 2020-07-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banner_pic',
        ),
    ]
